### ISSUE TITLE
Information request about TypeLoadException in SearchIndexClient constructor

### ISSUE THREAD

**Issue by RobertoPrevato** [Azure-Samples/search-dotnet-getting-started#15]
Hello,
I am using a piece of code similar to this one (from this repository):

```cs
string searchServiceName = configuration["SearchServiceName"];
string queryApiKey = configuration["SearchServiceQueryApiKey"];

SearchIndexClient indexClient = new SearchIndexClient(searchServiceName, "hotels", new SearchCredentials(queryApiKey));
```

And I am getting this exception from the constructor of `SearchIndexClient`:
```
TypeLoadException: Inheritance security rules violated by type: 'System.Net.Http.WebRequestHandler'. Derived types must either match the security accessibility of the base type or be less accessible.
Microsoft.Rest.ServiceClient.CreateRootHandler()
Microsoft.Azure.Search.SearchIndexClient..ctor(string searchServiceName, string indexName, SearchCredentials credentials)
```

The process running this code is hosting an ASP.NET MVC Core application using Framework 4.6.2

Could you please provide information, why is this error happening? I saw this exception reported in a number of different situations, but cannot find easily the root cause of the problem.

**Comment by RobertoPrevato** [comment]
This problem is mentioned here in StackOverflow [https://stackoverflow.com/questions/41048995/azure-search-error-inheritance-security-rules-violated](https://stackoverflow.com/questions/41048995/azure-search-error-inheritance-security-rules-violated). And here in GitHub [https://github.com/dotnet/corefx/issues/11100](https://github.com/dotnet/corefx/issues/11100).

**Comment by bitsforthought** [comment]
Closing as this issue is related to .NET Core, not this sample app specifically.

**Comment by RobertoPrevato** [comment]
Hi @brjohnstmsft,
Just for clarity, as I mentioned in my previous comment, I am using Framework 4.6.2 - not .NET Core. I am using ASP.NET MVC Core, but with Framework 4.6.2.

**Comment by bitsforthought** [comment]
@RobertoPrevato From the GitHub issue you linked above, it looks like this should be fixed if you're using `System.Net.Http` 4.3.1 or later. Did you try that?

I suggest you follow up on that issue. We are not the .NET team and can't really help you with this.

**Comment by RobertoPrevato** [comment]
Hi again, I just had opportunity to check;
* I am not referencing this assembly directly, it's a dependency of some package I am using (right now I don't have time to check which one) - maybe `Microsoft.AspNetCore.Mvc`
* The file version I see for System.Net.Http.dll used by my project is 4.6.24705.1
* I resorted to enabling CORS and contacting the REST API from the client using JavaScript, it's a pity I cannot do it from server side

I understand this is a problem of .NET team; thanks for your time, 
Best Regards

**Comment by bitsforthought** [comment]
@RobertoPrevato Given that you're still seeing the issue even with a newer version of `System.Net.Http`, I encourage you to post your findings on [this GitHub issue](https://github.com/dotnet/corefx/issues/11100) so the right people will be aware of it.
