### ISSUE TITLE
Cloning, then running this application, causes "Cannot get SerializationBinder because an ISerializationBinder was previously set."	error

### ISSUE THREAD

**Issue by open-environment** [Azure-Samples/search-dotnet-getting-started#22]
Downloaded source code, changed appsettings.json, then ran the DotNetHowTo solution. 

This occurs on the DeleteHotelsIndexIfExists method.

StackTrace:

	"   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\r\n   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\r\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)\r\n   at Microsoft.Rest.Azure.JsonSerializerExtensions.WithoutConverter(JsonSerializer serializer, JsonConverter converterToExclude)\r\n   at Microsoft.Rest.Azure.CloudErrorJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)\r\n   at Microsoft.Azure.Search.IndexesOperations.<GetWithHttpMessagesAsync>d__12.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Search.ExistsHelper.<ExistsFromGetResponse>d__0`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Search.IndexesOperationsExtensions.<ExistsAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Search.IndexesOperationsExtensions.Exists(IIndexesOperations operations, String indexName, SearchRequestOptions searchRequestOptions)\r\n   at AzureSearch.SDKHowTo.Program.DeleteHotelsIndexIfExists(SearchServiceClient serviceClient) in \\Repos\\search-dotnet-getting-started\\DotNetHowTo\\DotNetHowTo\\Program.cs:line 62\r\n   at AzureSearch.SDKHowTo.Program.Main(String[] args) in \\Repos\\search-dotnet-getting-started\\DotNetHowTo\\DotNetHowTo\\Program.cs:line 24"	string

**Comment by bitsforthought** [comment]
Related: https://github.com/Azure/azure-sdk-for-net/issues/3441

**Comment by bitsforthought** [comment]
@open-environment Thanks for reporting this. From the stack trace, it looks like a known issue with one of our dependencies, but strangely enough I can't seem to repro the problem on my machine. Can you please provide:

- The version of Visual Studio that you're using
- The versions of all dependencies listed under Microsoft.Azure.Search in the NuGet node of the project tree for the DotNetHowTo project

Thanks!

**Comment by open-environment** [comment]
**Additional information: the exception is thrown on DeleteHotelsIndexIfExists ONLY if the index doesn't already exist. If the index exists, then it runs properly.**

Visual Studio 2017 Professional 15.4.2
Microsoft.Azure.Search 3.0.4
Microsoft.Rest.ClientRuntime (2.3.7)
Newtonsoft.Json (10.0.1)
Microsoft.Rest.ClientRuntime.Azure (3.3.6)
Microsoft.Spatial (7.2.0)
System.Net.Http (4.3.2)
Microsoft.NETCore.Platforms (1.1.0)
Microsoft.Extensions.Configuration (2.0.0-preview1-final)
Microsoft.Extensions.Configuration.Json (2.0.0-preview1-final)

**Comment by bitsforthought** [comment]
Thanks @open-environment for the extra details. I couldn't repro because the index already existed.

This was caused by a [known issue](https://github.com/Azure/azure-sdk-for-net/issues/3441). I've worked around it by updating the sample's dependencies. Please pull the latest from the master branch, try again, and feel free to re-open this issue if you still see the problem.
