### ISSUE TITLE
Phrase search highlight going wild

### ISSUE THREAD

**Issue by mariusconjeaud** [Azure-Samples/search-dotnet-getting-started#25]
Hi,
Searching for phrase "leap of faith" in a text (with quotes to match whole phrase) works and gets only texts containing whole phrase. That's cool.

The problem is, when retrieving highlight on the text, it surrounds "leap", or "of" with `<em>` tags, even when they are used in another context, like "days `<em>`of`</em>` grays", or "frog `<em>`leap`</em>`".

Is that normal ? Is there a way to make it surround only the real match with an `<em>` tag ?

Thanks !

**Comment by mariusconjeaud** [comment]
Ok, i found this answer here : https://stackoverflow.com/questions/42411353/azure-search-highlights-for-phrases-with-double-quotes

Which says that only the Postings highlighter is presently implemented, and this highlighter highlights single words, not full phrase query.

**Comment by bitsforthought** [comment]
Hi @mariusWeceipt 

Glad you found the answer on StackOverflow. I'm closing this issue since it wasn't a problem with the sample per se. In the future feel free to ask such questions on StackOverflow and tag them with azure-search.

Thanks!
