### ISSUE TITLE
Samples need update

### ISSUE THREAD

**Issue by gopala000** [Azure-Samples/search-dotnet-getting-started#39]
I worked through couple of issues to make DotNetHowToAutoComplete sample to work:

1. Project has reference to a old jquery library and caused client errors.
2. Nugets like Azure.Spatial are outdated and caused compile/run time error.
3. Chrome browser now does not allow http for localhost run. I need to enable SSL to run/debug the app.

It will be helpful for devs checking out Azure Cognitive Search if the samples are kept current.

**Comment by mrcarter8** [comment]
Thanks for taking the time to make these updates.  The changes related to the referenced SDK version are great.  No concerns there.  I'm not sure about the changes to the JS and CSS files in the autocomplete sample, thought.  Could you explain more about why these were needed and what they do?

**Comment by gopala000** [comment]
Sample app had reference to some old jquery library that caused auto complete call to fail silently due to client side error. It will be good to bring client dependencies to current and verify if sample app works.

**Comment by HeidiSteen** [comment]
This issue is resolved. Closing the issue.
