### ISSUE TITLE
Recommended way to setup in .NET Core Dependency Injection?

### ISSUE THREAD

**Issue by xantari** [Azure-Samples/search-dotnet-getting-started#43]
Are there service collection methods to register the search client with .NET Core's DI framework?

None of the examples show this...

**Comment by bitsforthought** [comment]
@xantari There are no special methods for registering search client types in any DI container. You would have to register them like any non-framework type.

**Comment by xantari** [comment]
@brjohnstmsft You have the Microsoft.Azure.Extensions library that provides handy extension methods for registering the blob storage clients.

Why not the search clients?

**Comment by bitsforthought** [comment]
@xantari It's a good suggestion. I've filed an issue for this in the .NET SDK repo: https://github.com/Azure/azure-sdk-for-net/issues/11514

Closing this issue now. If this feature is added to the new SDK, it will be added to new samples as part of that. These samples are no longer actively maintained.
